"""empty message

Revision ID: 875abbf7ffa0
Revises: d83fcca22b41
Create Date: 2021-12-07 01:48:59.453465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875abbf7ffa0'
down_revision = 'd83fcca22b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
